layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options:
    - pushed
    - stars
  limit: 9
  exclude:
    archived: false
    # forks: true
    projects:
    - personal-website
    - 996.ICU
    - darknet
    - caffe-yolov3
    - CarlaTests
    - carla
    - https-github.com-cs61bl-362
    - Show-Attend-and-Tell

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: Yige Liu
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: yige-kristina-liu
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: CroMa Lab
    web_url: http://croma.eecs.umich.edu/croma.html
    image_url: http://croma.eecs.umich.edu/images/entries/full-size/croma-lab_logo_um-clear_square.png

  - name: Fouhey AI Lab
    web_url: http://fouheylab.eecs.umich.edu
    image_url: https://pbs.twimg.com/profile_images/905532722013229057/FIL1DVHL_400x400.jpg
